#!/bin/bash
#bspc monitor -d    ﳁ   ﭮ  
bspc monitor -d TERM WEB CODE MISC EDIT CHAT DISCORD MUSIC

bspc config border_width         2
bspc config focused_border_color "#928374"
bspc config normal_border_color "#282828"
